name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker image
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/my-image-name:latest -t $DOCKER_USERNAME/my-image-name:$(date +%s) --push .


     
